Don't specify a group for cron resource
The cron resource doesn't support a 'group' parameter and you get an
error like:

Error: Invalid parameter group on Cron[clean old logs] at
/root/pcci-configuration/modules/buildlogs/manifests/init.pp:49 on node
planck.nibalizer.com